#!/bin/bash

from="/home/macaroot"
to="/home/macaroot/dotfiles"

cp -pR $from/{.bash_profile,.bashrc,.gtkrc-2.0,.i3status.conf,.inputrc,Junk,pacgetto,.vimrc,.xinitrc,.Xresources} $to

mkdir -p $to/{.config,.i3,Junk}

cp -pR $from/.config/mimeapps.list $to/.config/mimeapps.list
cp -pR $from/.i3/config $to/.i3/config
cp -pR $from/Junk/ $to/

unset from
unset to

echo simming done
