#!/bin/bash

xsetwacom set "Wacom Cintiq 22HD Pad pad" MapToOutput DVI-0 && xsetwacom set "Wacom Cintiq 22HD Pen stylus" MapToOutput DVI-0 && xsetwacom set "Wacom Cintiq 22HD Pen eraser" MapToOutput DVI-0
